config/routes.rb
Bookkeeping::Application.routes.draw do

  devise_for :users

  devise_scope :user do
     root 'devise/registrations#new'
  end

  get 'dashboard' => 'dashboards#show'
  get 'finance_accounts' => 'finance_accounts#new'
  resources :entry_builders
  resources :entries
  resources :finance_accounts
  resources :income_statements
  resources :balance_sheets

end

app/models/income_statement.rb
class IncomeStatement
  include ActiveModel::Model

  attr_accessor :start_date, :end_date, :user, :revenues, :expenses

  def initialize(hash)
    @user = hash[:user]
    @start_date = hash[:start_date]
    @end_date = hash[:end_date]
    @revenues = @user.revenues
    @expenses = @user.expenses
  end

  def to_csv(options = {})
    CSV.generate(options) do |csv|
      self.revenues.each do |revenue|
        csv << [revenue.name,revenue.balance_between_dates(self.start_date, self.end_date).to_s]
      end
    end
  end

  def profit(start_date, end_date)
    self.revenues.balance_between_dates(start_date, end_date) - self.expenses.balance_between_dates(start_date, end_date)
  end

end

app/controllers/income_statements_controller.rb
class IncomeStatementsController < ApplicationController

  def index
    @income_statement = IncomeStatement.new(:user => current_user, :start_date => "2014-07-01", :end_date => "2014-07-09")
    respond_to do |format|
      format.html
      format.xls
    end
  end

end

app/views/income_statements/index.html.erb
<h1>Income Statement from July 1, 2014 to <%= Date.today %></h1>

<h3>Revenues</h3>
<% @income_statement.revenues.each do |revenue| %>
  <%= revenue.name %> - <%= revenue.balance_between_dates("2014-07-01", Date.today + 2.day) %>
  <br>
<% end %>
<h3>Total Revenues - <%= @income_statement.revenues.balance_between_dates("2014-07-01", Date.today) %></h3>

<br>
<h3>Expenses</h3>
<% @income_statement.expenses.each do |expense| %>
  <%= expense.name %> - <%= expense.balance_between_dates("2014-07-01", Date.today) %>
  <br>
<% end %>
<h3>Total Expenses - <%= @income_statement.expenses.balance_between_dates("2014-07-01", Date.today) %></h3>

<h3>Profit - <%= @income_statement.profit("2014-07-01", Date.today) %> </h3>


<p>
  Download:
  <%= link_to "Excel", income_statements_path(format: "xls") %>
</p>

app/views/income_statements/show.html.erb
<h1>Income Statement from July 1, 2014 to <%= Date.today %></h1>

<h3>Revenues</h3>
<% current_user.revenues.each do |account| %>
  <%= account.name %> - <%= account.balance_between_dates("2014-07-01", Date.today + 2.day) %>
  <br>
<% end %>
<h3>Total Revenues - <%= current_user.revenues.balance_between_dates("2014-07-01", Date.today) %></h3>

<br>
<h3>Expenses</h3>
<% current_user.expenses.each do |account| %>
  <%= account.name %> - <%= account.balance_between_dates("2014-07-01", Date.today) %>
  <br>
<% end %>
<h3>Total Expenses - <%= current_user.expenses.balance_between_dates("2014-07-01", Date.today) %></h3>

<h3>Profit - <%= current_user.revenues.balance_between_dates("2014-07-01", Date.today) - current_user.expenses.balance_between_dates("2014-07-01", Date.today) %> </h3>