config/routes.rb
Bookkeeping::Application.routes.draw do

  devise_for :users

  devise_scope :user do
     root 'devise/registrations#new'
  end

  get 'dashboard' => 'dashboards#show'
  get 'finance_accounts' => 'finance_accounts#new'
  resources :entry_builders
  resources :entries
  resources :finance_accounts
  resources :income_statements
  resources :balance_sheets

end

app/models/balance_sheet.rb
class BalanceSheet
  include ActiveModel::Model

  attr_accessor :as_of, :period, :user, :assets, :liabilities, :equities

  def initialize(hash)
    @user = hash[:user]
    @as_of = hash[:as_of]
    @period = hash[:period]
    @assets = @user.assets
    @liabilities = @user.liabilities
    @equities = @user.equities
  end

  def to_csv(options = {})
    CSV.generate(options) do |csv|
      self.line_items.each do |line_item|
        csv << self.line_item_array(line_item)
      end
    end
  end

  def line_item_array(line_item)
    [line_item.name, line_item.balance_as_of(self.as_of).to_s]
  end

end

app/controllers/balance_sheets_controller.rb
class BalanceSheetsController < ApplicationController

  def index
    @balance_sheet = BalanceSheet.new(:user => current_user, :as_of => "2014-12-31", :period => "Annual")
    @income_statement = IncomeStatement.new(:user => current_user, :start_date => "2014-01-01", :end_date => "2014-12-31")
    respond_to do |format|
      format.html
      format.xls
    end
  end

end

app/views/balance_sheets/index.html.erb
<h1>Balance Sheet as of <%= Date.today %></h1>

<h3>Asset</h3>
<% @balance_sheet.assets.each do |asset| %>
  <%= asset.name %>: <%= asset.balance_as_of(Date.today) %>
  <br>
<% end %>
<h3>Total Assets: <%= @balance_sheet.assets.balance_as_of(Date.today) %></h3>

<br>
<h3>Liabilities</h3>
<% @balance_sheet.liabilities.each do |liability| %>
  <%= liability.name %>: <%= liability.balance_as_of(Date.today) %>
  <br>
<% end %>
<h3>Total Liabilities: <%= @balance_sheet.liabilities.balance_as_of(Date.today) %></h3>

<br>
<h3>Owner's Equity</h3>
<% @balance_sheet.equities.each do |equity| %>
  <%= equity.name %>: <%= equity.balance_as_of(Date.today) %>
  <br>
<% end %>
Net income this period: <%= @income_statement.profit(THE_BEGINNING, Date.today) %>

<h3>Total Owner's Equity: <%= @balance_sheet.equities.balance_as_of(Date.today) + @income_statement.profit(THE_BEGINNING, Date.today)  %></h3>

<p>
  Download:
  <%= link_to "Excel", balance_sheets_path(format: "xls") %>
</p>

app/views/balance_sheets/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <!-- Report headers-->
      <Row>
        <Cell></Cell>
        <Cell><Data ss:Type="String"><%= @balance_sheet.user.email %></Data></Cell>
      </Row>
      <Row>
        <Cell></Cell>
        <Cell><Data ss:Type="String">Balance Sheet</Data></Cell>
      </Row>
      <Row>
        <Cell></Cell>
        <Cell><Data ss:Type="String"><%= @balance_sheet.period + "Balance Sheet as of " + @balance_sheet.as_of %></Data></Cell>
      </Row>

    <!-- Assets -->
    <Row>
      <Cell><Data ss:Type="String">Assets</Data></Cell>
    </Row>
    <% @balance_sheet.assets.each do |asset| %>
      <Row>
        <Cell><Data ss:Type="String"><%= asset.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= asset.balance_as_of(@balance_sheet.as_of) %></Data></Cell>
      </Row>
    <% end %>
    <Row>
      <Cell><Data ss:Type="String">Total Assets</Data></Cell>
      <Cell><Data ss:Type="Number"><%= @balance_sheet.user.assets.balance_as_of(@balance_sheet.as_of) %></Data></Cell>
    </Row>

    <Row>
      <Cell></Cell>
    </Row>

    <!-- Liabilities -->

    <Row>
      <Cell><Data ss:Type="String"><B>Liabilities</B></Data></Cell>
    </Row>
    <% @balance_sheet.liabilities.each do |liability| %>
      <Row>
        <Cell><Data ss:Type="String"><%= liability.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= liability.balance_as_of(@balance_sheet.as_of) %></Data></Cell>
      </Row>
    <% end %>
    <Row>
      <Cell><Data ss:Type="String">Total Liabilities</Data></Cell>
      <Cell><Data ss:Type="Number"><%= @balance_sheet.user.liabilities.balance_as_of(@balance_sheet.as_of) %></Data></Cell>
    </Row>

    <Row>
      <Cell></Cell>
    </Row>

    <!-- Owner's Equity -->
    <% @balance_sheet.equities.each do |equity| %>
      <Row>
        <Cell><Data ss:Type="String"><%= equity.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= equity.balance_as_of(@balance_sheet.as_of) %></Data></Cell>
      </Row>
    <% end %>
    <Row>
      <Cell><Data ss:Type="String">Net Income for period</Data></Cell>
      <Cell><Data ss:Type="Number"><%= @income_statement.profit(THE_BEGINNING, Date.today) %></Data></Cell>
    </Row>
    <Row>
      <Cell><Data ss:Type="String">Total Owner's Equity</Data></Cell>
      <Cell><Data ss:Type="Number"><%= @balance_sheet.user.equities.balance_as_of(@balance_sheet.as_of) + @income_statement.profit(THE_BEGINNING, Date.today) %></Data></Cell>
    </Row>


    </Table>
  </Worksheet>
</Workbook>